### ISSUE TITLE
ShareDBError: Missing version in ingested snapshot

### ISSUE THREAD

**Issue by MihanixA** [share/sharedb-mongo#108]
I am trying to fetch newly created document and I am getting the following error:
```
(internal/process/task_queues.js:75:11) {
code_share_backend_1    |   code: 'ERR_INGESTED_SNAPSHOT_HAS_NO_VERSION'
code_share_backend_1    | }
code_share_backend_1    | ShareDBError: Missing version in ingested snapshot. workspaces.603b7b1138d2b400114f55cd
code_share_backend_1    |     at Doc.ingestSnapshot (/app/node_modules/sharedb/lib/client/doc.js:177:15)
code_share_backend_1    |     at Query._ingestSnapshots (/app/node_modules/sharedb/lib/client/query.js:139:9)
code_share_backend_1    |     at Query._handleResponse (/app/node_modules/sharedb/lib/client/query.js:120:25)
code_share_backend_1    |     at Query._handleFetch (/app/node_modules/sharedb/lib/client/query.js:97:8)
code_share_backend_1    |     at Connection.handleMessage (/app/node_modules/sharedb/lib/client/connection.js:204:24)
code_share_backend_1    |     at StreamSocket.socket.onmessage (/app/node_modules/sharedb/lib/client/connection.js:142:18)
code_share_backend_1    |     at /app/node_modules/sharedb/lib/stream-socket.js:60:12
```
The fetch function looks like 
```
router.get("/", function(req, res) {
    const query = req.model.query('workspaces', {ownerId: req.user['user_id']});
    query.fetch(function (err) {
        if (err) {
            console.log(err);
            res.sendStatus(500);
        } else {
            const result = query.get();
            res.json(result);
        }
    });
});
```
What does this error mean? 
Could you suggest a way of solving this problem? 

Thank you 🙏 in advance

**Comment by ericyhwang** [comment]
That means there's no `v` (version) field present on the fetched doc.
* If you run that query directly in a Mongo shell, do all matching docs have a `_v` field?
* If not, were all docs matching that query created using sharedb? sharedb expects that collections it interacts with are always managed through sharedb.

**Comment by MihanixA** [comment]
Thx!
