### ISSUE TITLE
Fix Travis Build

### ISSUE THREAD

**Issue by curran** [share/sharedb-mongo#48]
The Travis build is *so close* to working (93% of tests passing), it's a shame the REAMDE gives the "build failing" impression for such a solid project.

Here's the Travis log pointing to failing cases:

```
  122 passing (59s)
  8 failing
  1) db "before each" hook:
     Uncaught ReferenceError: done is not defined
      at node_modules/sharedb/test/client/submit.js:1062:25
      at callEach (node_modules/sharedb/lib/client/doc.js:905:7)
      at node_modules/sharedb/lib/client/doc.js:882:24
      at Doc._emitResponseError (node_modules/sharedb/lib/client/doc.js:232:5)
      at Doc._handleFetch (node_modules/sharedb/lib/client/doc.js:242:24)
      at Connection.handleMessage (node_modules/sharedb/lib/client/connection.js:223:20)
      at StreamSocket.socket.onmessage (node_modules/sharedb/lib/client/connection.js:117:18)
      at node_modules/sharedb/lib/stream-socket.js:59:12
      at _combinedTickCallback (internal/process/next_tick.js:67:7)
      at process._tickCallback (internal/process/next_tick.js:98:9)
  2) db "after each" hook for "adds ops index":
     TypeError: Cannot read property 'call' of undefined
  
  3) mongo db indexes adds ops index:
     TypeError: Cannot read property 'commit' of undefined
      at Context.<anonymous> (test/test_mongo.js:41:14)
  4) db "after each" hook for "adds ops index":
     TypeError: Cannot read property 'call' of undefined
  
  5) mongo db connection via url string commit and query:
     Error: done() invoked with non-Error: {"code":5101,"message":"Already closed"}
      at test/test_mongo.js:362:27
      at index.js:9:43234
      at index.js:9:3627
      at DB.ShareDbMongo.getDbs (index.js:9:5923)
      at DB.ShareDbMongo.getCollection (index.js:9:3427)
      at DB.ShareDbMongo.query (index.js:9:43003)
      at test/test_mongo.js:361:12
      at index.js:9:11824
      at node_modules/mongodb/lib/collection.js:1150:18
      at handleCallback (node_modules/mongodb/lib/utils.js:96:56)
      at node_modules/mongodb/lib/collection.js:1239:5
      at node_modules/mongodb-core/lib/wireprotocol/2_4_support.js:419:9
      at _combinedTickCallback (internal/process/next_tick.js:67:7)
      at process._tickCallback (internal/process/next_tick.js:98:9)
  6) mongo db connection via url string "before each" hook for "delays queryPoll but not commit":
     TypeError: Cannot read property 'call' of undefined
  
  7) mongo db connection via url string "before each" hook for "delays queryPoll but not commit":
     TypeError: Cannot read property 'call' of undefined
  
  8) mongo db "after each" hook:
     TypeError: Cannot read property 'call' of undefined
 
```

**Comment by pypmannetjies** [comment]
We have switched to GitHub Actions
