### ISSUE TITLE
TypeError: callback is not a function

### ISSUE THREAD

**Issue by JensSteckhan** [share/sharedb-mongo#72]
I am trying to get the richt-text example to work and keep getting the error `callback is not a function`.
I am using mongodb v4.0.6, sharedb 1.0.0-beta.18 and sharedb-mongo 0.8.7.

This is my code:
```
(...)
var ShareDB = require('sharedb');
var richText = require('rich-text');
ShareDB.types.register(richText.type);

var sharedb = require('sharedb-mongo')('mongodb://localhost:27017/test');
var backend = new ShareDB({'db': sharedb});
(...)
```
When I run it, I get the following error and I have no idea why. 
It is reproduce both on a Windows machine and a Mac.
I guess this is a problem of sharedb-mongo?
```
C:\Dev\minutes\sharedb\examples\rich-text\node_modules\mongodb\lib\utils.js:123
    process.nextTick(function() { throw err; });
                                  ^

TypeError: callback is not a function
    at C:\Dev\minutes\sharedb\examples\rich-text\node_modules\sharedb-mongo\index.js:259:7
    at handleCallback (C:\Dev\minutes\sharedb\examples\rich-text\node_modules\mongodb\lib\utils.js:120:56)
    at C:\Dev\minutes\sharedb\examples\rich-text\node_modules\mongodb\lib\collection.js:1416:5
    at handleCallback (C:\Dev\minutes\sharedb\examples\rich-text\node_modules\mongodb\lib\utils.js:120:56)
    at C:\Dev\minutes\sharedb\examples\rich-text\node_modules\mongodb\lib\cursor.js:683:5
    at handleCallback (C:\Dev\minutes\sharedb\examples\rich-text\node_modules\mongodb-core\lib\cursor.js:171:5)
    at setCursorNotified (C:\Dev\minutes\sharedb\examples\rich-text\node_modules\mongodb-core\lib\cursor.js:515:3)
    at C:\Dev\minutes\sharedb\examples\rich-text\node_modules\mongodb-core\lib\cursor.js:599:16
    at queryCallback (C:\Dev\minutes\sharedb\examples\rich-text\node_modules\mongodb-core\lib\cursor.js:232:18)
    at C:\Dev\minutes\sharedb\examples\rich-text\node_modules\mongodb-core\lib\connection\pool.js:469:18
```

**Comment by ericyhwang** [comment]
Try updating to the latest `sharedb-mongo@1.0.0-beta.9` and see if that works - most of the recent fixes and changes have been published on 1.x-beta.

**Comment by alecgibson** [comment]
Closing due to inactivity.
