### ISSUE TITLE
Flaky tests

### ISSUE THREAD

**Issue by alecgibson** [share/sharedb-mongo#99]
We've got some flaky tests that were sometimes failing the build before [on Travis][1] and are still failing now [on GH Actions][2].

```
  1) db
       "after each" hook:
     Uncaught Error: Already closed
      at wrapErrorData (node_modules/sharedb/lib/client/connection.js:263:13)
      at Connection.handleMessage (node_modules/sharedb/lib/client/connection.js:191:11)
      at StreamSocket.socket.onmessage (node_modules/sharedb/lib/client/connection.js:142:18)
      at /home/travis/build/share/sharedb-mongo/node_modules/sharedb/lib/stream-socket.js:60:12
      at processTicksAndRejections (internal/process/task_queues.js:79:11)
  2) db
       "before each" hook for "subscribe bulk with readSnapshots rejectSnapshotRead special ignorable error":
     TypeError: Cannot read property 'call' of undefined
      at processImmediate (internal/timers.js:461:21)
  3) getOpsWithoutStrictLinking: true
       "after each" hook for "fetches ops 0-1 without fetching all ops":
     TypeError: Cannot read property 'close' of undefined
      at Context.<anonymous> (test/test_get_ops_without_strict_linking.js:36:13)
      at processImmediate (internal/timers.js:461:21)
```

[1]: https://travis-ci.org/github/share/sharedb-mongo/jobs/745926761
[2]: https://github.com/share/sharedb/pull/411/checks?check_run_id=1458446903

**Comment by alecgibson** [comment]
I wonder if at least the first failure is because of this test: https://github.com/share/sharedb/blob/1038607535f364050f675aeb60e9d5a78f4b0593/test/db.js#L27-L37

```js
    afterEach(function(done) {
      this.backend.close(done);
    });

    it('can call db.close() without callback', function(done) {
      create(function(err, db) {
        if (err) return done(err);
        db.close();
        done();
      });
    });
```

Here, we call `db.close()` twice: once in the test, and then again in the `afterEach` hook.

And in `sharedb-mongo`, this is what `close()` looks like: https://github.com/share/sharedb-mongo/blob/c6a4395eb76bd9185f6da46a078e408fe5f51737/index.js#L193-L209

Note that we call `this.getDbs`, which checks if we're already closed, and returns an error if so: https://github.com/share/sharedb-mongo/blob/c6a4395eb76bd9185f6da46a078e408fe5f51737/index.js#L111-L114

We could fix the upstream test, but I honestly feel like the real solution is just to check if we're already closed in `close()`, and early return if so. We could potentially even add a test for this to the upstream test suite, because I feel like you should be able to repeatedly call `close()` and everything should just be fine.

**Comment by alecgibson** [comment]
Looks like that didn't fix it...

https://github.com/share/sharedb-mongo/pull/101/checks?check_run_id=1487922405

**Comment by alecgibson** [comment]
Hopefully fixed by https://github.com/share/sharedb/pull/416 🤞
